# Generated by Django 3.2.13 on 2023-09-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdogustavo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('stat1', models.IntegerField()),
                ('stat2', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='motivos',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='peso',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='tamanho',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
