# Generated by Django 3.2.13 on 2023-09-02 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdogustavo', '0002_auto_20230902_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabeladata',
            old_name='stat1',
            new_name='statM',
        ),
        migrations.RenameField(
            model_name='tabeladata',
            old_name='stat2',
            new_name='statS',
        ),
        migrations.RemoveField(
            model_name='tabeladata',
            name='name',
        ),
    ]
