# Generated by Django 3.2.13 on 2023-09-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdogustavo', '0003_auto_20230902_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motivos',
            name='prioridade',
        ),
        migrations.AddField(
            model_name='motivos',
            name='ExpressividadeInGame',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
