# Generated by Django 3.2.13 on 2023-09-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdogustavo', '0004_auto_20230902_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemons',
            name='img',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motivos',
            name='ExpressividadeInGame',
            field=models.CharField(choices=[('G', 'Grande'), ('M', 'Média'), ('P', 'Pequena')], max_length=1),
        ),
    ]
