# Generated by Django 3.2.13 on 2023-09-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdogustavo', '0005_auto_20230902_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemons',
            name='color',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
