# Generated by Django 3.2.13 on 2023-09-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdogustavo', '0006_pokemons_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemons',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
